services:
  data_service:
    depends_on:
      database:
        condition: service_healthy
    build: data_service
    command: sh -c "
      diesel setup &&
      diesel migration generate --diff-schema create_match_data &&
      diesel migration run;
      cargo watch -x test"
    volumes:
      - ./data_service:/data_service
    env_file:
      - .env
  database:
    build: database
    env_file:
      - .env
    healthcheck:
      test: pg_isready -U $POSTGRES_USER
      interval: 5s
      timeout: 5s
      retries: 5
  adminer:
    image: adminer
    ports:
      - 8080:8080
