services:
  data_service:
    depends_on:
      database:
        condition: service_healthy
    build: data_service
    command: sh -c "
      diesel setup &&
      diesel migration generate --diff-schema create_match_data &&
      diesel migration run &&
      cargo watch -x run"
    volumes:
      - ./data_service:/data_service
    env_file:
      - env.txt
  database:
    build: database
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5
    env_file:
      - env.txt
  adminer:
    image: adminer
    ports:
      - 8080:8080
