name: Rust

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  rust_checks:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Build data_service
      working-directory: data_service
      run: cargo build --verbose
    - name: Test data_service
      working-directory: data_service
      run: cargo test --lib --bins --verbose
    - name: Check formatting
      working-directory: data_service
      run: cargo fmt --all -- --check --config format_generated_files=false
